### PR TITLE
warning category removed

### PR DESCRIPTION
**Pull request by capzDE**

### CODE REVIEW

**Comment by jannikvogel** [comment]
Once again: It is not the job of an ATC on VATSIM to police on things like VSOA restricted activities that may be conducted by unapproved members, just to mention one example. 
I do not understand the purpose of these messages other than policing members, which is not within the competence of a VATSIM ATC. 
I am strongly recommending to remove all those policing "warnings", SUPs are there to enforce policies not ATCOs.

**Comment by Calaelen** [comment]
I can understand the purpose of having a layer between  "ignoring it" and "sending a wallop" ... because most of the times a wallop results in the same as ignoring it. Hinting the pilot might help them as well if they didn't know? 

But more like a hint and not as policing.

**Comment by LeoKle** [comment]
I agree with @jannikvogel 
There should be no warnings, advisories would be preferable as these mistakes are primarily unintentional.

However to get a representative opinion it would be good if all member of @VATGER-Nav/edgg @VATGER-Nav/edww @VATGER-Nav/edmm could vote on this message with:
👍 if they would like these warnings to be removed
👎 if they would like to leave them in

**Comment by capzDE** [comment]
I'm with Karsten on this one. Having something between ignoring issues and immediately escalating things to supervisors who might not even be available at that time and/or who might not be incredibly helpful for one reason or another is important.

We can certainly argue about `.warncoc` and `.warnvsoa`, and if you want also about `.rwy` and `.twy`, but the others are literally the exact same thing anyone would tell pilots on voice. Maybe the section title "Warnings" was an unfortunate choice, but I fail to see how the content of these is supposed to be outside the purview of regular controllers on the network (or am I not allowed to explain the difference between startup and pushback, what hold short of means, etc. to the pilots and should always call a supervisor to have them explain it?).

**Review by LeoKle — CHANGES_REQUESTED** [review]
remove warnings, as voted for by majority of members

**Comment by capzDE** [comment]
Just to confirm: we remove _all_ the aliases in the "Warning" category?

**Comment by LeoKle** [comment]
remove the warnings category we already have a help section with aliases, that should be sufficient

**Comment by capzDE** [comment]
Removed warning category and all aliases therein

**Review by LeoKle — APPROVED** [review]

**Review by hannesaltmann — APPROVED** [review]

**Review by fpletz — APPROVED** [review]

**Pull request merged**
